Login_app/urls.py
from django.urls import path
from Login_app import views



app_name = 'Login_app'
urlpatterns = [
    path('', views.index, name="index"),
    path('register/', views.register, name="register"),
    path('login/', views.logIn, name="login"),
    path('user_login/', views.user_login, name="user_login"),
    path('user_logout/', views.logOut, name="logout")

]

p_user_authentication/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Login_app.urls'))
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Login_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    facebook_id = models.URLField()
    profile_pic = models.ImageField(upload_to="profile_pics/")

    def __str__(self):
        return self.user.username

Login_app/forms.py
from django import forms
from Login_app import models
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.PasswordInput()
    class Meta:
        model = User
        fields = ('username', 'password', 'email')

class UserInfoForm(forms.ModelForm):
    class Meta:
        model = models.UserInfo
        fields = ('facebook_id', 'profile_pic')

Login_app/views.py
from django.shortcuts import render
from Login_app import forms
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.models import User
from Login_app import models


# Create your views here.
def index(request):
    dict = {}
    if request.user.is_authenticated:
        current_user = request.user
        user_id = current_user.id
        user_basic_info = User.objects.get(pk=user_id)
        user_more_info = models.UserInfo.objects.filter(user__pk=user_id).first()
        dict = {
            'user_basic_info':user_basic_info,
            'user_more_info':user_more_info,

        }
    return render(request, 'login_app/index.html', context=dict)

def register(request):
    registered = False
    if request.method == "POST":
        user_form = forms.UserForm(data=request.POST)
        user_info_form = forms.UserInfoForm(data=request.POST, files=request.FILES)

        if user_form.is_valid() and user_info_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_info = user_info_form.save(commit=False)
            user_info.user = user


            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']

            user_info.save()
            registered = True

    else:
        user_form = forms.UserForm()
        user_info_form = forms.UserInfoForm()
    dict = {
        'registered':registered,
        'user_form':user_form,
        'user_info_form': user_info_form,
    }

    return render(request, 'login_app/register.html', context=dict)


def logIn(request):
    return render(request, 'login_app/Log_in.html', context={})

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('Login_app:index'))
            else:
                return HttpResponse ("the user is not active")
        else:
            return HttpResponse("The information is not valid")

    else:
        return HttpResponseRedirect(reverse('login_app/Log_in.html'))

@login_required
def logOut(request):
    logout(request)
    return HttpResponseRedirect(reverse('Login_app:index'))

templates/login_app/Log_in.html
<!DOCTYPE html>
{% extends 'login_app/base.html' %}
{% block content %}
<h1>Log in to the Website:</h1>
<form method="POST" action="{% url 'Login_app:user_login' %}">
    {% csrf_token %}
    <label for="username" >Username:</label>
    <input type="text" name="username" id="username" placeholder="Enter your username" required class="form-control"><br>
    <label for="password">Password:</label>
    <input type="password" name="password" id="password" placeholder="Enter your password" required class="form-control"><br>
    <input type="submit" name="submit" class="btn btn-success" value="Log In">
</form>
{% endblock %}

templates/login_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'Login_app:index' %}">MHR</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'Login_app:index' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'Login_app:logout' %}">Log Out</a>
                </li>
                {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Login_app:register' %}">Register</a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'Login_app:login' %}">Log In</a>
                </li>
                {% endif %}
              </ul>
              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
            </div>
        </div>
      </nav>

      <div class="container" style="padding-top: 25px;">
        {% block content %}

        {% endblock %}
      </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"></script>
</body>
</html>

templates/login_app/index.html
<!DOCTYPE html>
{% extends 'login_app/base.html' %}
{% block content %}
{% if user.is_authenticated %}
    <p>Hi, {{user_basic_info.username}}</p>
    <p>Your Email: {{user_basic_info.email}}</p>
    <a href="{{user_more_info.facebook_id}}">Facebook</a><br>
    <!-- <img src="{{user_more.info.profile_pic.url}}" alt="profile_pic" width="200px"> -->
     <!-- <p>Profile pic: {{ user_more_info.profile_pic.url}}</p> -->
     <img src="{{ user_more_info.profile_pic.url }}" alt="Profile Picture">

{% else %}
    <h1 class="alert alert-primary ">You have to LogIn to see you Infomations</h1>
{% endif %}
{% endblock %}

templates/login_app/register.html
<!DOCTYPE html>
{% extends 'login_app/base.html' %}
{% block content %}
{% if registered %}
<h1 class="alert alert-success">Registered Successfull</h1>
{% else %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ user_info_form.as_p }}
    <input type="submit" name="submit" value="Register" class="btn btn-primary">
</form>
{% endif %}
{% endblock %}